services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn task_manager_backend.wsgi --log-file -
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString